(asdf:defsystem "cl-cc-runtime-test"
  :description "Tests for cl-cc-runtime (cl-weave)."
  :version "0.1.0"
  :author "nerima-lisp"
  :license "MIT"
  :homepage "https://github.com/nerima-lisp/cl-cc-runtime"
  :depends-on ("cl-cc-runtime" "cl-weave")
  :pathname "tests"
  :serial t
  :components ((:file "package")
               (:file "consensus-tests")
               (:file "crypto-tests")
               (:file "continuous-profile-tests")
               (:file "deadlock-tests")
               (:file "frame-tests")
               (:file "gc-fr-tests")
               (:file "gc-stats-tests")
               (:file "gc-sweep-major-tests")
               (:file "gc-tests")
               (:file "gc-write-barrier-tests")
               (:file "heap-sanitizer-tests")
               (:file "heap-trace-tests")
               (:file "runtime-clos-tests")
               (:file "runtime-io-tests")
               (:file "runtime-serialize-tests")
               (:file "runtime-stdlib-3-image-tests")
               (:file "runtime-stdlib-3-os-tests")
               (:file "runtime-strings-chars-tests")
               (:file "runtime-tests-2")
               (:file "runtime-tests")
               (:file "value-tests")
               (:file "crdt-tests")
               (:file "cluster-tests")
               (:file "gpu-tests")
               (:file "metrics-tests")
               (:file "parallel-algo-tests")
               (:file "zerocopy-tests")
               (:file "signals-tests")
               (:file "reactive-tests")
               (:file "perf-tests")
               (:file "lockfree-tests")
               (:file "spsc-tests")
               (:file "hazard-tests")
               (:file "ebr-tests")
               (:file "rcu-tests")
               (:file "qsbr-tests")
               (:file "mvcc-tests")
               (:file "actor-tests")
               (:file "channel-tests")
               (:file "stm-tests")
               (:file "task-tests")
               (:file "future-tests")
               (:file "fiber-tests")
               (:file "scheduler-tests")
               (:file "event-loop-tests")
               (:file "effects-tests")
               (:file "allocator-tests")
               (:file "compress-tests")
               (:file "context-tests")
               (:file "async-generators-tests")
               (:file "runtime-stack-tests")
               (:file "gc-advanced-129-tests")
               (:file "ratelimit-tests")
               (:file "gc-data-tests")
               (:file "frame-tests-2")
               (:file "sync-tests")
               (:file "runtime-ops-tests")
               (:file "runtime-math-io-tests")
               (:file "runtime-pathnames-tests")
               (:file "runtime-conditions-tests")
               (:file "image-tests")
               (:file "async-tests")
               (:file "portable-tests")
               (:file "gc-workers-tests")
               (:file "gc-major-sweep-extra-tests")
               )
  :perform (asdf:test-op (op system)
             (declare (ignore op system))
             (unless (uiop:symbol-call :cl-weave :run-all :reporter :spec :pass-with-no-tests nil)
               (error "cl-cc-runtime tests failed"))))
