;;;; Read-Copy-Update (FR-380)
(in-package :cl-cc/runtime)
(defvar *rt-rcu-readers* (make-hash-table))
(defvar *rt-rcu-mutex* (rt-make-mutex))
(defvar *rt-rcu-cond* (rt-make-condition-variable))
(defun %rt-rcu-thread () sb-thread:*current-thread*)
(defun rt-rcu-read-lock ()
  (rt-with-mutex (*rt-rcu-mutex*)
    (incf (gethash (%rt-rcu-thread) *rt-rcu-readers* 0)))
  nil)
(defun rt-rcu-read-unlock ()
  (rt-with-mutex (*rt-rcu-mutex*)
    (let* ((thread (%rt-rcu-thread))
           (n (max 0 (1- (gethash thread *rt-rcu-readers* 0)))))
      (if (zerop n)
          (remhash thread *rt-rcu-readers*)
          (setf (gethash thread *rt-rcu-readers*) n))
      (when (zerop (hash-table-count *rt-rcu-readers*))
        (rt-condition-notify-all *rt-rcu-cond*))))
  nil)
(defun rt-rcu-assign-pointer (place new) (setf (symbol-value place) new))
(defun rt-rcu-dereference (place) (symbol-value place))
(defmacro rt-with-rcu-read (() &body body)
  `(unwind-protect (progn (rt-rcu-read-lock) ,@body)
     (rt-rcu-read-unlock)))
(defun rt-rcu-synchronize (&key timeout)
  "Block until every RCU reader active when this was called has exited its
read-side critical section (RT-RCU-READ-UNLOCK), so memory
RT-RCU-ASSIGN-POINTER made unreachable is then safe to reclaim. With
TIMEOUT and readers still active once it elapses, returns NIL rather than
blocking forever. The wait loop used to re-pass the original TIMEOUT to
every RT-CONDITION-WAIT instead of a shrinking remaining duration -- see
RT-BARRIER-WAIT's docstring in sync.lisp for why that matters."
  (rt-with-remaining-timeout (remaining timeout)
    (rt-with-mutex (*rt-rcu-mutex* :timeout timeout)
      (loop while (> (hash-table-count *rt-rcu-readers*) 0)
            do (let ((r (remaining)))
                 (when (and timeout (<= r 0)) (return-from rt-rcu-synchronize nil))
                 (unless (rt-condition-wait *rt-rcu-cond* *rt-rcu-mutex* :timeout r)
                   (return-from rt-rcu-synchronize nil))))))
  t)
(defun rt-rcu-call (fn &rest args)
  (rt-rcu-synchronize)
  (apply fn args))
(defun rt-rcu-init ()
  (clrhash *rt-rcu-readers*)
  t)
