;;;; regex.lisp -- a small, dependency-free regular expression engine.

(in-package #:cl-cc/runtime)

(defstruct (rt-regex (:constructor %make-rt-regex (pattern expression)))
  pattern expression)

(defun %regex-error (pattern position format-control &rest args)
  (error "Invalid regular expression ~S at ~D: ~?" pattern position format-control args))

(defun rt-regex-compile (pattern)
  "Compile PATTERN. Supports literals, ., [], ^, $, grouping, |, *, + and ?."
  (check-type pattern string)
  (let ((i 0) (n (length pattern)))
    (labels
        ((peek () (and (< i n) (char pattern i)))
         (take () (prog1 (peek) (incf i)))
         (parse-atom ()
           (let ((c (take)))
             (unless c (%regex-error pattern i "expected an atom"))
             (case c
               (#\( (let ((e (expr)))
                       (unless (eql (take) #\))
                         (%regex-error pattern i "missing )"))
                       e))
               (#\. '(:any))
               (#\^ '(:bol))
               (#\$ '(:eol))
               (#\[ (let ((negated (when (eql (peek) #\^) (take) t))
                          (items nil) (closed nil))
                      (loop while (peek)
                            do (if (eql (peek) #\])
                                   (progn (take) (setf closed t) (return))
                                   (let ((first (if (eql (peek) #\\) (progn (take) (or (take) #\\)) (take))))
                                     (if (eql (peek) #\-)
                                         (progn (take)
                                                (let ((last (if (eql (peek) #\\) (progn (take) (or (take) #\\)) (take))))
                                                  (unless (and last (char<= first last))
                                                    (%regex-error pattern i "invalid character range"))
                                                  (push (list :range first last) items)))
                                         (push (list :char first) items)))))
                      (unless closed (%regex-error pattern i "missing ]"))
                      (list :class negated (nreverse items))))
               (#\\ (let ((e (take)))
                       (unless e (%regex-error pattern i "trailing escape"))
                       (case e
                         (#\d '(:class nil ((:range #\0 #\9))))
                         (#\D '(:class t ((:range #\0 #\9))))
                         (#\w '(:class nil ((:range #\a #\z) (:range #\A #\Z) (:range #\0 #\9) (:char #\_))))
                         (#\s '(:class nil ((:char #\Space) (:char #\Tab) (:char #\Newline) (:char #\Return))))
                         (otherwise (list :char e)))))
               (otherwise (list :char c)))))
         (piece ()
           (let ((a (parse-atom)))
             (case (peek)
               (#\* (take) (list :star a))
               (#\+ (take) (list :plus a))
               (#\? (take) (list :opt a))
               (otherwise a))))
         (seq ()
           (let ((parts nil))
             (loop while (and (peek) (not (member (peek) '(#\) #\|))))
                   do (push (piece) parts))
             (if parts (cons :seq (nreverse parts)) '(:empty))))
         (expr ()
           (let ((left (seq)))
             (if (eql (peek) #\|) (progn (take) (list :alt left (expr))) left))))
      (let ((expression (expr)))
        (when (peek) (%regex-error pattern i "unexpected character ~C" (peek)))
        (%make-rt-regex pattern expression)))))

(defun %regex-class-member-p (char node)
  (let ((member (some (lambda (item)
                        (case (first item)
                          (:char (char= char (second item)))
                          (:range (char<= (second item) char (third item)))))
                      (third node))))
    (if (second node) (not member) member)))

(defun %regex-match-node (node string position end)
  (case (first node)
    (:empty (list position))
    (:char (and (< position end) (char= (second node) (char string position)) (list (1+ position))))
    (:any (and (< position end) (list (1+ position))))
    (:class (and (< position end) (%regex-class-member-p (char string position) node) (list (1+ position))))
    (:bol (and (= position 0) (list position)))
    (:eol (and (= position end) (list position)))
    (:seq (reduce (lambda (positions child)
                    (remove-duplicates (mapcan (lambda (p) (%regex-match-node child string p end)) positions)))
                  (rest node) :initial-value (list position)))
    (:alt (remove-duplicates (nconc (%regex-match-node (second node) string position end)
                                   (%regex-match-node (third node) string position end))))
    ((:star :plus :opt)
     (let* ((minimum (if (eql (first node) :plus) 1 0))
            (results (if (zerop minimum) (list position) nil))
            (frontier (list position)))
       (dotimes (ignored (if (eql (first node) :opt) 1 most-positive-fixnum))
         (let ((next (remove position (remove-duplicates
                                       (mapcan (lambda (p) (%regex-match-node (second node) string p end)) frontier)))))
           (unless next (return))
           (setf results (nconc results next) frontier next)))
       (if (and (eql (first node) :plus) (not results)) nil results)))))

(defun rt-regex-match-p (regex string &key (start 0) end)
  "Return true when REGEX matches STRING from START through END."
  (let ((r (if (typep regex 'rt-regex) regex (rt-regex-compile regex)))
        (limit (or end (length string))))
    (not (null (member limit (%regex-match-node (rt-regex-expression r) string start limit))))))

(defun rt-regex-search (regex string &key (start 0) end)
  "Return (start . end) for the first match, or NIL."
  (let ((r (if (typep regex 'rt-regex) regex (rt-regex-compile regex)))
        (limit (or end (length string))))
    (loop for position from start to limit
          for finishes = (%regex-match-node (rt-regex-expression r) string position limit)
          when finishes do (return (cons position (apply #'max finishes))))))
